name: Publish
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: "Get latest code"
      uses: actions/checkout@v3

    - name: "Sync files"
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.SFTP_USERNAME }}
        server: ${{ secrets.SFTP_SERVER }}
        ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
        local_path: './*'
        remote_path: ${{ secrets.SFTP_REMOTE_PATH }}

    - name: "Deploy project"
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SFTP_SERVER }}
        port: 22
        username: "kaneeldias"
        key: ${{ secrets.SFTP_PRIVATE_KEY }}
        script: cd ${{ secrets.SFTP_REMOTE_PATH }} && npm ci && npm run build

