name: PR buildx

on:
  pull_request:
    branches:
      - master

jobs:
  builD:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
        env:
          API_PATH: ${{secrets.API_PATH}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
          FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      - run: npm ci
      - run: npm run build --if-present
